BENCHMARK_SYMBOL = "SPY"

# Fast, ultra-liquid universe for 0-2 DTE trading with tight $0.01-$0.02 spreads
FAST_UNIVERSE = [
    "SPY",
    "QQQ",
    "IWM",
    "NVDA",
    "TSLA",
    "AMD",
    "AAPL",
    "AMZN",
    "META",
    "MSFT",
    "COIN",
    "MSTR",
]

# Default active universe on branch 'short' is the ultra-liquid subset
UNIVERSE = FAST_UNIVERSE

# Extended hackathon universe for reference / full universe scanning if requested
FULL_UNIVERSE = [
    # ============================================================
    # INFORMATION TECHNOLOGY / SOFTWARE / SEMICONDUCTORS
    # ============================================================
    "AAPL",
    "MSFT",
    "NVDA",
    "AVGO",
    "ORCL",
    "CRM",
    "ADBE",
    "CSCO",
    "ACN",
    "IBM",
    "INTU",
    "NOW",
    "QCOM",
    "AMD",
    "TXN",
    "AMAT",
    "MU",
    "LRCX",
    "KLAC",
    "ADI",
    "MRVL",
    "INTC",
    "NXPI",
    "MCHP",
    "ON",
    "MPWR",
    "CDNS",
    "SNPS",
    "ANSS",
    "FTNT",
    "PANW",
    "CRWD",
    "PLTR",
    "APP",
    "ADSK",
    "ROP",
    "APH",
    "KEYS",
    "DELL",
    "HPQ",
    
    # ============================================================
    # COMMUNICATION SERVICES / INTERNET / MEDIA
    # ============================================================
    "GOOGL",
    "META",
    "NFLX",
    "TMUS",
    "T",
    "VZ",
    "CMCSA",
    "CHTR",
    "DIS",
    "WBD",
    "TTWO",
    "EA",
    "RBLX",
    "PINS",
    "SNAP",
    "SPOT",
    "LYV",

    # ============================================================
    # CONSUMER DISCRETIONARY / RETAIL / TRAVEL
    # ============================================================
    "AMZN",
    "TSLA",
    "HD",
    "LOW",
    "TJX",
    "COST",
    "ORLY",
    "AZO",
    "ROST",
    "CMG",
    "MCD",
    "SBUX",
    "NKE",
    "BKNG",
    "MAR",
    "HLT",
    "GM",
    "F",
    "DRI",
    "YUM",
    "DHI",
    "LEN",
    "PHM",
    "TGT",
    "EBAY",
    "ETSY",
    "CVNA",
    "UBER",
    "ABNB",
    "DASH",
    "LULU",
    "DECK",
    "ULTA",
    "DPZ",
    "MGM",

    # ============================================================
    # CONSUMER STAPLES
    # ============================================================
    "WMT",
    "PG",
    "KO",
    "PEP",
    "PM",
    "MO",
    "MDLZ",
    "CL",
    "KMB",
    "GIS",
    "HSY",
    "KHC",
    "SYY",
    "KR",
    "KDP",
    "EL",
    "STZ",

    # ============================================================
    # HEALTHCARE / PHARMA / BIOTECH / MEDTECH
    # ============================================================
    "LLY",
    "UNH",
    "JNJ",
    "ABBV",
    "MRK",
    "PFE",
    "BMY",
    "AMGN",
    "GILD",
    "VRTX",
    "REGN",
    "ISRG",
    "ABT",
    "TMO",
    "DHR",
    "SYK",
    "BSX",
    "MDT",
    "ELV",
    "CI",
    "HUM",
    "CVS",
    "MCK",
    "COR",
    "ZBH",
    "RMD",
    "HCA",
    "BDX",
    "ALGN",
    "BIIB",
    "MRNA",
    "DXCM",
    "GEHC",
    "IQV",

    # ============================================================
    # FINANCIALS / BANKS / BROKERS / EXCHANGES / PAYMENTS
    # ============================================================
    "JPM",
    "BAC",
    "WFC",
    "C",
    "GS",
    "MS",
    "BLK",
    "SCHW",
    "USB",
    "PNC",
    "TFC",
    "COF",
    "AXP",
    "BK",
    "STT",
    "CME",
    "ICE",
    "SPGI",
    "MCO",
    "V",
    "MA",
    "PYPL",
    "COIN",
    "HOOD",
    "AIG",
    "MET",
    "PRU",
    "ALL",
    "TRV",
    "CB",

    # ============================================================
    # INDUSTRIALS / AEROSPACE / DEFENSE / TRANSPORT / MACHINERY
    # ============================================================
    "CAT",
    "DE",
    "GE",
    "HON",
    "RTX",
    "LMT",
    "NOC",
    "GD",
    "BA",
    "UPS",
    "FDX",
    "UNP",
    "CSX",
    "NSC",
    "ETN",
    "EMR",
    "PH",
    "ITW",
    "MMM",
    "WM",
    "RSG",
    "CARR",
    "OTIS",
    "JCI",
    "CMI",
    "PCAR",
    "URI",
    "FAST",
    "VRSK",
    "CTAS",
    "ADP",
    "GWW",

    # ============================================================
    # ENERGY / OIL / GAS / OILFIELD SERVICES
    # ============================================================
    "XOM",
    "CVX",
    "COP",
    "EOG",
    "SLB",
    "HAL",
    "OXY",
    "PSX",
    "VLO",
    "MPC",
    "ET",
    "WMB",
    "KMI",
    "OKE",
    "BKR",

    # ============================================================
    # MATERIALS / CHEMICALS / MINING
    # ============================================================
    "FCX",
    "NEM",
    "NUE",
    "STLD",
    "LIN",
    "APD",
    "SHW",
    "DOW",
    "DD",
    "CE",

    # ============================================================
    # UTILITIES / REAL ESTATE
    # ============================================================
    "NEE",
    "DUK",
    "SO",
    "AEP",
    "SRE",
    "D",
    "PLD",
    "AMT",
    "EQIX",
    "CCI",

    # ============================================================
    # HIGH-BETA / THEMATIC / SPECIAL-SITUATION
    # ============================================================
    "MSTR",
    "SNOW",
    "DDOG",
    "NET",
    "ZS",
    "OKTA",
    "MDB",
    "RIVN",
    "LCID",

    # ============================================================
    # HACKATHON VOLATILITY & GAMMA EXPANSION (ADDITIONS)
    # ============================================================
    # Leveraged / Broad Benchmark ETFs
    "QQQ",
    "IWM",
    "TQQQ",
    "SQQQ",
    "SOXL",
    "SOXS",
    "SMH",
    "XBI",
    "KRE",
    "XLE",
    "XLF",
    "GLD",
    "SLV",
    "TLT",
    "BITO",
    "SPCX",  # SPAC & Special Situations ETF

    # High-Beta Tech & AI Ecosystem
    "SMCI",
    "ARM",
    "TSM",
    "PATH",
    "IOT",
    "U",
    "AI",

    # Crypto Proxies & High-Beta Fintech
    "MARA",
    "RIOT",
    "CLSK",
    "CORZ",
    "CIFR",
    "SQ",
    "AFRM",
    "UPST",
    "SOFI",
    "NU",

    # Consumer / Retail / Space / High-Beta Growth
    "DKNG",
    "PENN",
    "RDDT",
    "MELI",
    "SE",
    "BABA",
    "PDD",
    "JD",
    "CELH",
    "MNST",
    "ASTS",
    "JOBY",

    # Biotech & Health Volatility
    "NVO",
    "CRSP",
    "EXAS",
    "BNTX",
    "SMMT",
    "IONS",
    "CYTK",

    # Energy, Uranium & Power Growth
    "ALB",
    "SQM",
    "CCJ",
    "UUUU",
    "CEG",
    "VST",

    # Real Estate & High Short Interest / Squeeze Favorites
    "OPEN",
    "Z",
    "RDFN",
    "GME",
    "AMC",
    "CHPT",
    "RUN",
    "ENPH",
    "SEDG",
    "FSLR",
    "PLUG",
]