from __future__ import annotations

import sys
from datetime import date, datetime, timedelta
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from alpaca.common.enums import Sort
from alpaca.data.requests import OptionBarsRequest, OptionTradesRequest
from alpaca.data.timeframe import TimeFrame

from alpaca_client.client import get_option_data_client, get_trading_client
from backtest.option_candidates import generate_candidate_symbols
from strategy.option_selector import parse_occ_symbol

WORKING_CONTRACTS = [
    "AAPL241220P00150000",
    "AAPL241220C00300000",
]
TARGET_START = datetime(2024, 6, 3)
TARGET_END = datetime(2024, 6, 10)


def fetch_historical_window(contract: str) -> tuple[list[dict], list[dict]]:
    client = get_option_data_client()
    bars_df = client.get_option_bars(
        OptionBarsRequest(
            symbol_or_symbols=[contract],
            timeframe=TimeFrame.Day,
            start=TARGET_START,
            end=TARGET_END,
            sort=Sort.ASC,
        )
    ).df
    trades_df = client.get_option_trades(
        OptionTradesRequest(
            symbol_or_symbols=[contract],
            start=TARGET_START,
            end=TARGET_END,
            sort=Sort.ASC,
        )
    ).df
    return bars_df.reset_index().to_dict(orient="records"), trades_df.reset_index().to_dict(orient="records")


def print_contract_metadata(contract: str) -> None:
    bars, trades = fetch_historical_window(contract)
    expiration, option_type, strike = parse_occ_symbol(contract)
    try:
        metadata = get_trading_client().get_option_contract(contract)
        underlying = metadata.underlying_symbol
    except Exception as exc:
        underlying = "(metadata unavailable)"
        print(f"metadata warning: {type(exc).__name__}: {exc}")

    print("=" * 80)
    print(f"contract: {contract}")
    print(f"underlying: {underlying}")
    print(f"expiration: {expiration.isoformat()}")
    print(f"strike: {strike}")
    print(f"option type: {option_type}")
    print(f"bar rows: {len(bars)}")
    print(f"trade rows: {len(trades)}")
    if bars:
        print(f"first bar ts: {bars[0].get('timestamp')}")
        print(f"last bar ts: {bars[-1].get('timestamp')}")
    if trades:
        print(f"first trade ts: {trades[0].get('timestamp')}")
        print(f"last trade ts: {trades[-1].get('timestamp')}")


def inspect_generator_against_known_contracts() -> None:
    decision_date = datetime(2024, 6, 5, 12, 0, 0)
    underlying_price = 195.87
    generated = generate_candidate_symbols(
        underlying="AAPL",
        underlying_price=underlying_price,
        decision_date=decision_date,
        min_dte=7,
        max_dte=60,
        strike_range_pct=0.15,
        strike_step=1.0,
    )

    print("\n=== generator diagnostics ===")
    print(f"decision_date: {decision_date.isoformat()}")
    print(f"generator range: min_dte={7}, max_dte={60}, strike_range_pct={0.15}")
    print(f"underlying_price used by generator: {underlying_price}")
    print(f"generated candidate count: {len(generated)}")

    for contract in WORKING_CONTRACTS:
        expiration, option_type, strike = parse_occ_symbol(contract)
        dte = (expiration - decision_date.date()).days
        in_range = 7 <= dte <= 60
        strike_around = abs(strike - underlying_price) <= underlying_price * 0.15
        print(f"\ncontract {contract}")
        print(f"  parsed expiration: {expiration.isoformat()}")
        print(f"  dte: {dte}")
        print(f"  strike: {strike}")
        print(f"  strike within +/-15% of underlying price: {strike_around}")
        print(f"  logically in generator range: {in_range and strike_around}")
        print(f"  generated: {contract in generated}")

        if in_range and strike_around:
            assert contract in generated, f"{contract} should have been generated by the current generator for this date/price"

    # Also test a broader fallback to prove the generator can produce the known contract when the range is widened.
    wider = generate_candidate_symbols(
        underlying="AAPL",
        underlying_price=underlying_price,
        decision_date=decision_date,
        min_dte=180,
        max_dte=220,
        strike_range_pct=0.50,
        strike_step=0.5,
    )
    print(f"\nWider-range generation count for 180..220 dte and +/-50% strikes: {len(wider)}")
    print(f"Known working contract in widened candidate set: {'AAPL241220P00150000' in wider}")


if __name__ == "__main__":
    print("=== confirmed historical OCC contracts ===")
    for contract in WORKING_CONTRACTS:
        print_contract_metadata(contract)

    inspect_generator_against_known_contracts()
    print("\nDiagnosis: this is not a malformed OCC encoding bug in the generator for the current 7..60 day / +/-15% range.")
    print("The known working contracts are outside the generator's current historical window and strike band, so they are not expected to appear.")
    print("The remaining issue is genuine historical-data sparsity in the selected candidate range, not a missing OCC encoding convention.")
